version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locker-manager-frontend
    environment:
        NODE_ENV: production
        PORT: 43000
    ports:
      - "43000:3000"
    restart: always